#version: '3.1'

services:
  mariadb:
    container_name: devops-mariadb
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /Users/masungil/db_data/devops:/var/lib/mysql:rw
    user: mysql
    environment:
      MARIADB_DATABASE: koreatech_db
      MARIADB_USER: koreatech
      MARIADB_PASSWORD: 1004koreatech
      MARIADB_ROOT_PASSWORD: 1004koreatech
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - my_bridge_network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: devops-redis
    networks:
      - my_bridge_network

  was1:
    image: masungil/devops:0.1
    ports:
      - 8090:8090
    container_name: devops-was1
    depends_on:
      - redis
      - mariadb
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge